### 《利用python进行数据分析》第四章

In [5]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [6]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 16.5 ms


In [7]:
%time for _ in range(10): my_list2 = my_list * 2

Wall time: 170 ms


In [8]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[ 0.32148014,  0.46201035, -0.67229324],
       [ 0.34433388, -0.11450017,  1.4252854 ]])

In [9]:
data * 10

array([[ 3.21480145,  4.62010349, -6.72293241],
       [ 3.44333879, -1.14500175, 14.25285404]])

In [10]:
data + data

array([[ 0.64296029,  0.9240207 , -1.34458648],
       [ 0.68866776, -0.22900035,  2.85057081]])

In [11]:
data.shape

(2, 3)

In [12]:
data.dtype

dtype('float64')

##### 创建ndarray数组

In [14]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
import numpy as np
np.zeros(10)
np.zeros((3,6))
np.empty((2, 3, 2))
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
import numpy as np
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1
arr2
arr1.dtype
arr2.dtype
arr = np.array([1, 2, 3, 4, 5])
arr.dtype
float_arr = arr.astype(np.float64)
float_arr
float_arr.dtype
arr = np.array([3.2, 1.2, -2.5, -3.1, 12.9])
arr
arr.dtype
arr.astype(np.int32)
numeric_strings = np.array(['1.23', '-9.6', '42.5'])
numeric_strings.astype(np.float64)

array([ 1.23, -9.6 , 42.5 ])

In [51]:
import numpy as np
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380])
calibers.dtype # float64
int_array.astype(calibers.dtype)
empty_uint32 = np.empty(8, dtype='u4')
empty_uint32
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
1 / arr
arr ** 0.5
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2
# 不同大小数组之间的运算叫做广播
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

##### 基本的索引和切片

In [62]:
import numpy as np
arr = np.arange(10)
arr
arr[5]
arr[5:8]
arr[-3:-1]
arr_slice = arr[5:8]
arr_slice
# 对切片的操作会作用与原数组
arr_slice[1] = 123456
arr_slice
arr
arr_slice.copy()

array([     5, 123456,      7])

In [76]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0][2]
arr2d[0, 2]
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d
arr3d[0]
old_values = arr3d[0].copy()
old_values
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

##### 二维数组切片

In [78]:
import numpy as np
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 9, 9]
])
arr[:1, -2:]
arr[:2, 1:]


array([[2, 3],
       [5, 6]])

##### 布尔索引

In [94]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names
data
names == 'Bob'
print(data[names == 'Bob'])
print(data[names == 'Bob', 2:])
print(data[names != 'Bob'])
print(data[~(names == 'Bob')])
cond = names == 'Bob'
data[~cond]
mask = (names == 'Bob') | (names == 'Will')
data[mask]
data[data < 0] = 0
data
data[names != 'Joe'] = 7
data

[[ 0.28157271  0.94252746 -0.49478915 -1.61105169]
 [ 0.71306952  0.00970295  0.69322475 -1.0194867 ]]
[[-0.49478915 -1.61105169]
 [ 0.69322475 -1.0194867 ]]
[[-0.10317684  0.76924845  1.38943143  0.72447456]
 [-0.38252517 -0.72382272 -0.18079278 -1.27588834]
 [ 1.42839234  0.80194166  0.03514212 -0.34605425]
 [ 0.85495215 -0.12103004 -0.26046608 -0.78659709]
 [-0.1621414   1.33922832 -0.32953234 -0.74196179]]
[[-0.10317684  0.76924845  1.38943143  0.72447456]
 [-0.38252517 -0.72382272 -0.18079278 -1.27588834]
 [ 1.42839234  0.80194166  0.03514212 -0.34605425]
 [ 0.85495215 -0.12103004 -0.26046608 -0.78659709]
 [-0.1621414   1.33922832 -0.32953234 -0.74196179]]


array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.76924845, 1.38943143, 0.72447456],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.85495215, 0.        , 0.        , 0.        ],
       [0.        , 1.33922832, 0.        , 0.        ]])

##### 花式索引

In [103]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr
arr[[4, 3, 0, 6]]
arr[[-1, -3, -5]]

arr = np.arange(32)
arr = arr.reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

##### 数组置换和轴对换

转置是重塑的⼀种特殊形式，它返回的是源数据的视图（不会进
⾏任何复制操作）。数组不仅有transpose⽅法，还有⼀个特殊
的T属性

In [127]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr
arr.T
arr1d = np.random.randn(6, 3)
arr1d
np.dot(arr1d.T, arr1d)
arr2d = np.arange(16).reshape((2, 2, 4))
print(type(arr2d))
print(arr2d)
# 任何时候你都要保持清醒，告诉自己第一个方括号“[]”为 0轴 ，第二个方括号为 1轴
# 此时，transpose转换关系就清晰了
# arr2d.transpose((1, 0, 2))
arr2d.transpose((2, 0, 1))

<class 'numpy.ndarray'>
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])